In [2]:
import tensorflow as tf

In [10]:
frase = tf.constant('Ola, Mundo!')
tf.print(frase)

Ola, Mundo!


In [11]:
print(frase)

tf.Tensor(b'Ola, Mundo!', shape=(), dtype=string)


In [7]:
print('Versão: {0}'.format(tf.__version__))

Versão: 2.3.0


In [4]:
# Create a constant tensor A
A = tf.constant([[4, 3], [6, 1]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1]])>

In [8]:
# Create a Variable tensor A
B = tf.Variable([[1, 2], [3, 4]])
B

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [9]:
# Concatenate Columns
AB_concat = tf.concat(values = [A, B], axis = 1)
AB_concat

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 1, 2],
       [6, 1, 3, 4]])>

In [10]:
# Concatenate Lines
AB_concat = tf.concat(values = [A, B], axis = 0)
AB_concat

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1],
       [1, 2],
       [3, 4]])>

In [11]:
tensor = tf.zeros(shape = [3,4], dtype = tf.int32)
tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

In [12]:
tensor = tf.ones(shape = [3,4], dtype = tf.int32)
tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])>

In [13]:
reshape_tensor = tf.reshape(tensor = tensor, shape = [4,3])
reshape_tensor

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])>

In [15]:
tensor_random = tf.random.uniform(shape = [3,4])
tensor_random

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.29551315, 0.1913495 , 0.34002388, 0.22078037],
       [0.62476635, 0.4635837 , 0.8978201 , 0.48126388],
       [0.4291284 , 0.98188305, 0.403957  , 0.4868313 ]], dtype=float32)>

In [16]:
reshape_tensor = tf.reshape(tensor = tensor_random, shape = [4,3])
reshape_tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.29551315, 0.1913495 , 0.34002388],
       [0.22078037, 0.62476635, 0.4635837 ],
       [0.8978201 , 0.48126388, 0.4291284 ],
       [0.98188305, 0.403957  , 0.4868313 ]], dtype=float32)>

In [18]:
# Typecast a tensor
tensor = tf.constant([[4.2, 5.8], [7.5, 4.5], [8.9, 9.4]], dtype = tf.float32)
tensor_as_int = tf.cast(tensor, tf.int32)
print(tensor)
print(tensor_as_int)

tf.Tensor(
[[4.2 5.8]
 [7.5 4.5]
 [8.9 9.4]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[4 5]
 [7 4]
 [8 9]], shape=(3, 2), dtype=int32)


In [20]:
# Transpose a tensor
a = tf.transpose(tensor_as_int)
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 7, 8],
       [5, 4, 9]])>

In [23]:
# Tensor Multiplication
A = tf.constant([[1, 2], [3, 4]])
V = tf.constant([[4], [1]])
AV = tf.matmul(A, V)
print(AV)

# Element-wise Multiplication
AV = tf.multiply(A, V)
print(AV)

tf.Tensor(
[[ 6]
 [16]], shape=(2, 1), dtype=int32)
tf.Tensor(
[[4 8]
 [3 4]], shape=(2, 2), dtype=int32)


In [27]:
# Creating a Identity Matrix
tensor = tf.constant([[4.2, 5.8], [7.5, 4.5], [8.9, 9.4]])
rows, columns = tensor.shape
print('rows:', rows, 'columns:', columns)

tensor_identity = tf.eye(num_rows = rows, num_columns = columns, dtype = tf.int32)
print(tensor_identity)

tensor_identity = tf.eye(num_rows = 3, num_columns = 3, dtype = tf.int32)
print(tensor_identity)

rows: 3 columns: 2
tf.Tensor(
[[1 0]
 [0 1]
 [0 0]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 0 0]
 [0 1 0]
 [0 0 1]], shape=(3, 3), dtype=int32)
